name: Azure Machine Learning training and deployment
on:
  push:
    branches:
      - "main"
      - "dev"
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      id: install_dependencies
      run: |
        python -m pip install azureml-core azureml-pipeline numpy pandas
        
    - name: Create Compute
      id: create_compute
      env:
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        WORKSPACE_NAME: ${{ secrets.WORKSPACE }}
        AML_TENANT_ID: ${{ secrets.AML_TENANT_ID }}
        AML_PRINCIPAL_ID: ${{ secrets.AML_PRINCIPAL_ID }}
        AML_PRINCIPAL_PASS: ${{ secrets.AML_PRINCIPAL_PASS }}
      run: |
        python compute/create_compute_target.py

    - name: Run Training
      id: run_training
      env:
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        WORKSPACE_NAME: ${{ secrets.WORKSPACE }}
        AML_TENANT_ID: ${{ secrets.AML_TENANT_ID }}
        AML_PRINCIPAL_ID: ${{ secrets.AML_PRINCIPAL_ID }}
        AML_PRINCIPAL_PASS: ${{ secrets.AML_PRINCIPAL_PASS }}
      run: |
        python training/training_pipeline.py
      
    #- name: Delete Compute
    #  id: delete_compute
    #  env:
    #    SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    #    RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
    #    WORKSPACE_NAME: ${{ secrets.WORKSPACE }}
     #   AML_TENANT_ID: ${{ secrets.AML_TENANT_ID }}
     #   AML_PRINCIPAL_ID: ${{ secrets.AML_PRINCIPAL_ID }}
     #   AML_PRINCIPAL_PASS: ${{ secrets.AML_PRINCIPAL_PASS }}
     # run: |
     #   python compute/delete_compute_target.py
     
    - name: Deploy Scoring
      id: run_scoring
      env:
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        WORKSPACE_NAME: ${{ secrets.WORKSPACE }}
        AML_TENANT_ID: ${{ secrets.AML_TENANT_ID }}
        AML_PRINCIPAL_ID: ${{ secrets.AML_PRINCIPAL_ID }}
        AML_PRINCIPAL_PASS: ${{ secrets.AML_PRINCIPAL_PASS }}

      run: |
        python scoring/aci_deploy.py
